<?php

namespace Tests\Feature\Http\Controllers\Auth;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Auth\ChangePasswordController
 */
class ChangePasswordControllerTest extends TestCase
{
    /**
     * @test
     */
    public function change_password_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->patch(route('auth.change_password'), [
            // TODO: send request data
        ]);

        $response->assertRedirect($this->redirectTo);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_change_password_form_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->get(route('auth.change_password'));

        $response->assertOk();
        $response->assertViewIs('auth.change_password');
        $response->assertViewHas('user');

        // TODO: perform additional assertions
    }

    // test cases...
}
