<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\ContentPagesController
 */
class ContentPagesControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.content_pages.create'));

        $response->assertOk();
        $response->assertViewIs('admin.content_pages.create');
        $response->assertViewHas('category_ids');
        $response->assertViewHas('tag_ids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contentPage = factory(\App\ContentPage::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->delete(route('admin.content_pages.destroy', [$content_page]));

        $response->assertRedirect(route('admin.content_pages.index'));
        $this->assertDeleted($admin);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contentPage = factory(\App\ContentPage::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.content_pages.edit', [$content_page]));

        $response->assertOk();
        $response->assertViewIs('admin.content_pages.edit');
        $response->assertViewHas('content_page');
        $response->assertViewHas('category_ids');
        $response->assertViewHas('tag_ids');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.content_pages.index'));

        $response->assertOk();
        $response->assertViewIs('admin.content_pages.index');
        $response->assertViewHas('content_pages');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function mass_destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post(route('admin.content_pages.mass_destroy'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contentPage = factory(\App\ContentPage::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.content_pages.show', [$content_page]));

        $response->assertOk();
        $response->assertViewIs('admin.content_pages.show');
        $response->assertViewHas('content_page');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post(route('admin.content_pages.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.content_pages.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $contentPage = factory(\App\ContentPage::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->put(route('admin.content_pages.update', [$content_page]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.content_pages.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
