<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\ItemsController
 */
class ItemsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->get(route('admin.items.create'));

        $response->assertOk();
        $response->assertViewIs('admin.items.create');
        $response->assertViewHas('surveys');
        $response->assertViewHas('questions');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $item = \App\Item::factory()->create();
        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->delete(route('admin.items.destroy', [$item]));

        $response->assertRedirect(route('admin.items.index'));
        $this->assertDeleted($admin);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $item = \App\Item::factory()->create();
        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->get(route('admin.items.edit', [$item]));

        $response->assertOk();
        $response->assertViewIs('admin.items.edit');
        $response->assertViewHas('item');
        $response->assertViewHas('surveys');
        $response->assertViewHas('questions');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->get(route('admin.items.index'));

        $response->assertOk();
        $response->assertViewIs($template);
        $response->assertViewHas('row');
        $response->assertViewHas('gateKey');
        $response->assertViewHas('routeKey');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function mass_destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->post(route('admin.items.mass_destroy'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function perma_del_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $item = \App\Item::factory()->create();
        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->delete(route('admin.items.perma_del', ['id' => $item->id]));

        $response->assertRedirect(route('admin.items.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function restore_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $item = \App\Item::factory()->create();
        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->post(route('admin.items.restore', ['id' => $item->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.items.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $item = \App\Item::factory()->create();
        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->get(route('admin.items.show', [$item]));

        $response->assertOk();
        $response->assertViewIs('admin.items.show');
        $response->assertViewHas('item');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->post(route('admin.items.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.items.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $item = \App\Item::factory()->create();
        $user = \App\User::factory()->create();

        $response = $this->actingAs($user)->put(route('admin.items.update', [$item]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.items.show', $id));

        // TODO: perform additional assertions
    }

    // test cases...
}
