<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\LoguseragentsController
 */
class LoguseragentsControllerTest extends TestCase
{
    use RefreshDatabase;

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $loguseragent = factory(\App\Loguseragent::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->delete(route('admin.loguseragents.destroy', [$loguseragent]));

        $response->assertRedirect(route('admin.loguseragents.index'));
        $this->assertDeleted($admin);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $loguseragent = factory(\App\Loguseragent::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.loguseragents.edit', [$loguseragent]));

        $response->assertOk();
        $response->assertViewIs('admin.loguseragents.edit');
        $response->assertViewHas('loguseragent');
        $response->assertViewHas('users');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.loguseragents.index'));

        $response->assertOk();
        $response->assertViewIs($template);
        $response->assertViewHas('row');
        $response->assertViewHas('gateKey');
        $response->assertViewHas('routeKey');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function mass_destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->post(route('admin.loguseragents.mass_destroy'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $loguseragent = factory(\App\Loguseragent::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->get(route('admin.loguseragents.show', [$loguseragent]));

        $response->assertOk();
        $response->assertViewIs('admin.loguseragents.show');
        $response->assertViewHas('loguseragent');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $loguseragent = factory(\App\Loguseragent::class)->create();
        $user = factory(\App\User::class)->create();

        $response = $this->actingAs($user)->put(route('admin.loguseragents.update', [$loguseragent]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.loguseragents.index'));

        // TODO: perform additional assertions
    }

    // test cases...
}
