<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\QuestionnairesController
 */
class QuestionnairesControllerTest extends TestCase
{
    use DatabaseTransactions;

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.questionnaires.create'));

        $response->assertOk();
        $response->assertViewIs('admin.questionnaires.create');
        $response->assertViewHas('surveys');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $questionnaire = \App\Questionnaire::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->delete(route('admin.questionnaires.destroy', [$questionnaire]));

        $response->assertRedirect(route('admin.questionnaires.index'));
        $this->assertSoftDeleted($admin);

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $questionnaire = \App\Questionnaire::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.questionnaires.edit', [$questionnaire]));

        $response->assertOk();
        $response->assertViewIs('admin.questionnaires.edit');
        $response->assertViewHas('questionnaire');
        $response->assertViewHas('surveys');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.questionnaires.index'));

        $response->assertOk();
        $response->assertViewIs($template);
        $response->assertViewHas('row');
        $response->assertViewHas('gateKey');
        $response->assertViewHas('routeKey');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function mass_destroy_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->post(route('admin.questionnaires.mass_destroy'), [
            // TODO: send request data
        ]);

        $response->assertOk();

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function perma_del_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $questionnaire = \App\Questionnaire::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->delete(route('admin.questionnaires.perma_del', ['id' => $questionnaire->id]));

        $response->assertRedirect(route('admin.questionnaires.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function restore_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $questionnaire = \App\Questionnaire::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->post(route('admin.questionnaires.restore', ['id' => $questionnaire->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.questionnaires.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $questionnaire = \App\Questionnaire::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.questionnaires.show', [$questionnaire]));

        $response->assertOk();
        $response->assertViewIs('admin.questionnaires.show');
        $response->assertViewHas('survey');
        $response->assertViewHas('questionnaire');
        $response->assertViewHas('responses');

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->post(route('admin.questionnaires.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.questionnaires.index'));

        // TODO: perform additional assertions
    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {
        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $questionnaire = \App\Questionnaire::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->put(route('admin.questionnaires.update', [$questionnaire]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.questionnaires.show', $id));

        // TODO: perform additional assertions
    }

    // test cases...
}
