<?php

namespace Tests\Feature\Http\Controllers\Admin;

use Illuminate\Foundation\Testing\DatabaseTransactions;
use Illuminate\Foundation\Testing\WithFaker;
use Tests\TestCase;

/**
 * @see \App\Http\Controllers\Admin\SurveysController
 */
class SurveysControllerTest extends TestCase
{
    use DatabaseTransactions;

    /**
     * @test
     */
    public function clone_returns_an_ok_response()
    {

        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Survey::factory()->create();

        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.surveys.clone', [$survey]));

        $response->assertRedirect(route('admin.surveys.show', $newSurvey));


    }

    /**
     * @test
     */
    public function create_returns_an_ok_response()
    {


        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.surveys.create'));

        $response->assertOk();
        $response->assertViewIs('admin.surveys.create');
        $response->assertViewHas('institutions');
        $response->assertViewHas('categories');
        $response->assertViewHas('groups');


    }

    /**
     * @test
     */
    public function destroy_returns_an_ok_response()
    {


        $survey = \App\Survey::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->delete(route('admin.surveys.destroy', [$survey]));

        $response->assertRedirect(route('admin.surveys.index'));
        $this->assertSoftDeleted($survey);


    }

    /**
     * @test
     */
    public function edit_returns_an_ok_response()
    {


        $survey = \App\Survey::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.surveys.edit', [$survey]));

        $response->assertOk();
        $response->assertViewIs('admin.surveys.edit');
        $response->assertViewHas('survey');
        $response->assertViewHas('institutions');
        $response->assertViewHas('categories');
        $response->assertViewHas('groups');


    }

    /**
     * @test
     */
    public function index_returns_an_ok_response()
    {


        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.surveys.index'));

        $response->assertOk();
        $response->assertViewIs('admin.surveys.index');
        $response->assertViewHas('surveys');


    }

    /**
     * @test
     */
    public function mass_destroy_returns_an_ok_response()
    {


        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->post(route('admin.surveys.mass_destroy'), [
            // TODO: send request data
        ]);

        $response->assertOk();


    }

    /**
     * @test
     */
    public function perma_del_returns_an_ok_response()
    {

        $survey = \App\Survey::factory()->create();

        $survey->delete();
        
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->delete(route('admin.surveys.perma_del', ['id' => $survey->id]));

        $response->assertRedirect(route('admin.surveys.index'));


    }

    /**
     * @test
     */
    public function restore_returns_an_ok_response()
    {


        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
        $survey = \App\Survey::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->post(route('admin.surveys.restore', ['id' => $survey->id]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.surveys.index'));


    }

    /**
     * @test
     */
    public function show_returns_an_ok_response()
    {


        $survey = \App\Survey::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->get(route('admin.surveys.show', [$survey]));

        $response->assertOk();
        $response->assertViewIs('admin.surveys.show');
        $response->assertViewHas('survey');
        $response->assertViewHas('questionnaires');
        $response->assertViewHas('items');
        $response->assertViewHas('duplicates');


    }

    /**
     * @test
     */
    public function store_returns_an_ok_response()
    {


        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->post(route('admin.surveys.store'), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.surveys.index'));


    }

    /**
     * @test
     */
    public function update_returns_an_ok_response()
    {

        $this->markTestIncomplete('This test case was generated by Shift. When you are ready, remove this line and complete this test case.');

        $survey = \App\Survey::factory()->create();
        $user = $this->create_user('admin');

        $response = $this->actingAs($user)->put(route('admin.surveys.update', [$survey]), [
            // TODO: send request data
        ]);

        $response->assertRedirect(route('admin.surveys.show', $id));


    }

    // test cases...
}
