<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>New Questionnaire Submitted</title>
</head>
<body>
    <h2>New Questionnaire Submitted</h2>
    
    <p>A new questionnaire has been submitted for the survey: <strong>{{ $survey_title }}</strong></p>
    
    <p><strong>Survey Alias:</strong> {{ $survey_alias }}</p>
    
    <p><strong>View Questionnaire:</strong></p>
    <p><a href="{{ $questionnaire_url }}">{{ $questionnaire_url }}</a></p>
    
    <hr>
    <p><small>This email was automatically generated by {{ config('app.name') }}.</small></p>
</body>
</html>